config/routes.rb
Rails.application.routes.draw do
  get 'faces/index'

  get 'faces/vertical'

  get 'faces/compare'
  get 'faces/audit_report'
  get 'faces/audit_process'
  post 'faces/audit_process'
  get 'faces/spellcheck'

  get 'faces/uom'

  get 'faces/col_comp'
  
  get 'faces/result'
  get 'faces/help_ver'
  get 'faces/help_uom'
  get 'faces/duplication'  
  post 'faces/duplication_process'
  get 'faces/save_file'
  
  get 'faces/spell_process'

  get 'faces/uom_method'
 
  get 'faces/vert_process'

  get 'faces/vert_help'
  
  get 'faces/consicutive'

  get 'faces/consicutive_process'

  post 'faces/save_file'

  post 'faces/uom_method' 
  
  post 'faces/spell_process'

  post 'faces/vert_process'

  post 'faces/vert_help'
  
  post 'faces/result'
  post 'faces/help_ver'
  post 'faces/help_uom'
  post 'faces/consicutive'
  post 'faces/consicutive_process'
 
  get 'faces/welookup'
   
  post 'faces/welookup'

  get 'faces/pilot'
   
  post 'faces/pilot'

   root 'faces#index'

end

app/models/face.rb
require 'roo'
require 'spreadsheet'
require 'iconv'
require 'csv'
class Face < ActiveRecord::Base
  def self.com_vertical(file1,file2)
  t=0
   CSV.open("#{Rails.root}/public/files/Vertical_Audit.csv","w") do |csv|
   csv << ["Item ID","Name","Value","Unit"]
   CSV.foreach(file1.tempfile,:encoding=>("ISO8859"))do |line|
        t=t+1
       next if t == 1
        x = line ; id=x.shift
        ad=[]
        ad=x.each_slice(3).to_a
        ad.each do|p|
       break if p[0] == nil
       unless p[1] == nil
        csv << [id] + p
       end
       end
       end
    end

   t=0
    CSV.open("#{Rails.root}/public/files/Vertical_Shipment.csv","w") do |csv|
    csv << ["Item ID","Name","Value","Unit"]
    CSV.foreach(file2.tempfile,:encoding=>("ISO8859"))do |line|
        t=t+1
       next if t == 1
        x = line ; id=x.shift
        ad=[]
        ad=x.each_slice(3).to_a
        ad.each do|p|
       break if p[0] == nil
       unless p[1] == nil
        csv << [id] + p
       end
       end
       end
   end
 end
 def self.audit_task(file1,fmonth,anual,reporttyp)
  if reporttyp=="Monthly"
  tns=[]
  name=[]
  n=1;t=0;
  a=[];b=[];c=[];d=[];e=[];g=[];quality=[];final=[];a3=[];first=[];
  name1=[];a1=[];a2=[];totsq=[];totsa=[];totsater=[];err=[];qual=[];totsqu=[];totsam=[];qualper=[];errper=[];errp=[];qualp=[];toterr=[];toter=[];final=[]
  totsqur=[];totsamr=[];toterrr=[],totpr=[];totp=[];check=[]
  CSV.open("#{Rails.root}/public/out/outpro.csv" ,"w") do |csv|
  csv << ["Name","Projectnames","Total sku","Sample count","FinalErrorCount","Error(%)","Quality(%)"]
    file1.each do|kfile|
     unless kfile[0] == nil
        ff=CSV.read(kfile[0].tempfile)
          check=ff[0][0]        
        if check=="Name"
        ff.each_with_index do |row ,i| 
          next if i==0
          csv << [row[0],row[1],row[2].to_f,row[3].to_f,row[4]]
        end
      else
        wui=kfile[n].to_f
        projectname=kfile[2]   
        ff=CSV.read(kfile[0].tempfile)
        ff.shift
        name=ff.collect{|row| row[1]}.uniq

           name.each do |i|
            @tns=ff.select{|row| i==row[1]}
            ff.each do|row|
              if i==row[1] && row[2] != nil
                c << row [2]
                next if row[3] == nil || row[3] == "NOTA" || row[8] == "Updated/Not Uptated" || row[8] == "Not Updated" 
                e << row[8]
              end
                 b=@tns.length
                 g=e.length
                 d=c.length
                 a=g.to_f/d.to_f*100.0
                 quality=100.0-a.to_f
                if wui ==7 || wui ==""
                  b=@tns.length
                  g=e.length
                  d=c.length
                  a=(g.to_f/d.to_f*100.0).round(2)
                  quality=(100.0-a.to_f).round(2)
                else
                  b=(wui/7*b).round(2)
                  d=(wui/7*d).round(2)
                  g=g
                  a=(g.to_f/d.to_f*100.0).round(2)
                  quality=(100.0-a.to_f).round(2)
                end
            end
              c.clear
              e.clear
              csv << [i,projectname,b,d,g,a,quality]
          end
      end    
    end
  end
end

    CSV.open("#{Rails.root}/public/files/#{fmonth}_#{anual}_audit_report.csv" ,"w") do |final|
    final << ["Name","ProjectNames","Total sku","Sample count","FinalErrorCount","Error(%)","Quality(%)"]    
    z=CSV.read("#{Rails.root}/public/out/outpro.csv")
      a1=z.collect{|s| s[0]}.uniq
       a1.each_with_index do |p,index|
          next if index == 0
            z.each do |s|
              if p==s[0]
                totp << s[1]
                totsq << s[2].to_f
                totsa << s[3].to_f
                toter << s[4].to_f
                err << s[5].to_f
                qual << s[6].to_f
              end
                totsqu = totsq.inject(:+)
                totsam = totsa.inject(:+)
                toterr = toter.inject(:+)
                totsqur = (totsqu.to_f).round(2)
                totsamr = (totsam.to_f).round(2)
                toterrr = (toterr.to_f).round(2)
                qualp = qual.inject(:+)
                errp = err.inject(:+)
                errper = (toterr.to_f/totsam.to_f*100.0).round(2)
                qualper = (100-errper).round(2)
                totpr=totp.uniq.to_s.gsub!(/[^0-9A-Za-z,-,]/, '')
            end
              totsq.clear
              totsa.clear
              toter.clear
              err.clear
              qual.clear
              totp.clear
              final << [p,totpr,totsqur,totsamr,toterrr,errper,qualper]
        end
        
   end
else
  tns=[]
  name=[]
  n=1;t=0;
  a=[];b=[];c=[];d=[];e=[];g=[];quality=[];final=[];a3=[];first=[];
  name1=[];a1=[];a2=[];totsq=[];totsa=[];totsater=[];err=[];qual=[];totsqu=[];totsam=[];qualper=[];errper=[];errp=[];qualp=[];toterr=[];toter=[];final=[]
  totsqur=[];totsamr=[];toterrr=[],totpr=[];totp=[]
  CSV.open("#{Rails.root}/public/out/outpro.csv" ,"w") do |csv|
  csv << ["Name","Projectnames","Total sku","Sample count","FinalErrorCount","Error(%)","Quality(%)"]
    file1.each do|kfile|
     unless kfile[0] == nil
        ff=CSV.read(kfile[0].tempfile)
        ff.each_with_index do |row ,i| 
          next if i==0
          csv << [row[0],row[1],row[2].to_f,row[3].to_f,row[4]]
        end    
    end
  end
end
    CSV.open("#{Rails.root}/public/files/#{anual}_audit_report.csv" ,"w") do |final|
    final << ["Name","ProjectNames","Total sku","Sample count","FinalErrorCount","Error(%)","Quality(%)"]    
    z=CSV.read("#{Rails.root}/public/out/outpro.csv")
      a1=z.collect{|s| s[0]}.uniq

       a1.each_with_index do |p,index|
          next if index == 0
            z.each do |s|
              if p==s[0]
                totp << s[1]
                totsq << s[2].to_f
                totsa << s[3].to_f
                toter << s[4].to_f
                err << s[5].to_f
                qual << s[6].to_f
              end
                totsqu = totsq.inject(:+)
                totsam = totsa.inject(:+)
                toterr = toter.inject(:+)
                totsqur = (totsqu.to_f).round(2)
                totsamr = (totsam.to_f).round(2)
                toterrr = (toterr.to_f).round(2)
                qualp = qual.inject(:+)
                errp = err.inject(:+)
                errper = (toterr.to_f/totsam.to_f*100.0).round(2)
                qualper = (100-errper).round(2)
                totpr=totp.uniq.to_s.gsub(/\W/,'')
              end
              totsq.clear
              totsa.clear
              toter.clear
              err.clear
              qual.clear
              totp.clear
              final << [p,totpr,totsqur,totsamr,toterrr,errper,qualper]
        end
   end
end
end    
 def self.comparison
  File.open("#{Rails.root}/public/files/Output_comparison.csv","w") do |c| 
  a=File.open("#{Rails.root}/public/files/Vertical_Audit.csv","r",:headers=>'true').collect{|o|o.chomp}
  b=File.open("#{Rails.root}/public/files/Vertical_Shipment.csv","r",:headers=>'true').collect{|o|o.chomp}
    if a != b
      c.puts b - a
    end
    end
 end
     
 def self.uoms(file1,file2)
  t=0
   CSV.open("#{Rails.root}/public/files/Vertical_UOM_Audit.csv","w") do |csv|
   csv << ["Item ID","Name","Value","Unit"]
   CSV.foreach(file1.tempfile,:encoding=>("ISO8859"))do |line|

       t=t+1
    next if t == 1
     x = line ; id=x.shift
     ad=[]
     ad=x.each_slice(3).to_a
     ad.each do|p|
    break if p[0] == nil
    unless p[1] == nil
     csv << [id] + p
    end
     end
     end
     end

      s=0
      t=0
      CSV.open("#{Rails.root}/public/files/UOM_file_Output.csv","w") do |csv|
      csv << ["Item ID","Name","Value","Unit"]
        a=CSV.read("#{Rails.root}/public/files/Vertical_UOM_Audit.csv")
        b=CSV.read(file2.tempfile)
         
          a.each do |i|
          t=t+1
            next if t==1
            if i[3]!=nil
                 b.each do |j|
                 s=j
            break if i[3]==s[0]
            end
            unless i[3]==s[0]
                 csv << i
            end
          end
        end
      end
  end
   
   def self.verticals(file1)
     
   CSV.open("#{Rails.root}/public/files/Vertical_Output.csv","w+") do |csv|
   csv << ["Item ID","Name","Value","Unit"]
   CSV.foreach(file1.tempfile,:encoding => 'iso-8859-1:utf-8')do |line|
   next if line[0].to_s.match(/\A[+-]?\d+?(\.\d+)?\Z/) == nil
      
      x = line ; id=x.shift

      sd = x.shift(5) 

      sdd = sd.each_slice(1).to_a

      dd = ["HTML","PT Sourced PDF","RS Website","RSPDF","SKU Accounting Flag"] 

      ad = x.each_slice(3).to_a 

      add = dd,sd 

      ad1 = add.reduce(&:zip).map(&:flatten) 

      ad3 = ad1 + ad 

      ad3.each do|p|

    break if p[0] == nil
    unless p[1] == nil
      csv << [id] + p 
    end
    end
    end
    end
   end

=begin   def self.spell_check(file1)
    #  speller = FFI::Hunspell.dict('en_GB')
       f=File.open(file1.tempfile,"r").read
           f=f.split(" ").uniq!
       f.each do |i|
          next if i == i.upcase
          next if  i =~ /\d/
           i = i.strip
           i = i.gsub(/\W+/,' ')
           if speller.check?(i)

           else
              File.open("/home/altius/anand-ror/Firstop.csv","a+"){|file|file.puts("#{i}")}
           end
     end
            f=File.open("/home/altius/anand-ror/Firstop.csv","r").read
              f=f.split(" ").uniq!
               f.each do |i|
                 next if i == i.upcase
                   next if  i =~ /\d/
                     next if  i.length <= 2
                       i = i.strip
                         i = i.gsub(/\W+/,' ')
                 if speller.check?(i)

                  else
                    puts "#{i.chomp}"
               File.open("/home/altius/mahesh/UI_Task/public/files/Output_Spellcheck.csv","w+") do |c|
               c.puts("#{i}")
                 end
              end


   end
=end

def self.consecutive(file1,filename)
out=[]

app/controllers/faces_controller.rb
require 'csv'
class FacesController < ApplicationController
  def index
      @face=Face.all
  end
   def audit_report
      @face=Face.new
    end
    def audit_process 
      wu=[];f1=[];f2=[];f3=[];f4=[];f5=[];f6=[];f7=[];f8=[];f9=[];f10=[];f11=[];f12=[];file1=[];fmonth=[],anual=[];reporttyp=[]
    anual=params[:faces][:year]
    reporttyp=params[:faces][:reporttype]
    fmonth=params[:faces][:month]
    f1 << params[:faces][:aa]
    f2 << params[:faces][:bb]
    f3 << params[:faces][:cc]
    f4 << params[:faces][:dd]
    f5 << params[:faces][:ee]
    f6 << params[:faces][:ff]
    f7 << params[:faces][:gg]
    f8 << params[:faces][:hh]
    f9 << params[:faces][:ii]
    f10 << params[:faces][:jj]
    f11 << params[:faces][:kk]
    f12 << params[:faces][:ll]
    f1 << params[:faces][:a]
    f2 << params[:faces][:b]
    f3 << params[:faces][:c]
    f4 << params[:faces][:d]
    f5 << params[:faces][:e]
    f6 << params[:faces][:f]
    f7 << params[:faces][:g]
    f8 << params[:faces][:h]
    f9 << params[:faces][:i]
    f10 << params[:faces][:j]
    f11 << params[:faces][:k]
    f12 << params[:faces][:l]
    f1 << params[:faces][:aaa]
    f2 << params[:faces][:bbb]
    f3 << params[:faces][:ccc]
    f4 << params[:faces][:ddd]
    f5 << params[:faces][:eee]
    f6 << params[:faces][:fff]
    f7 << params[:faces][:ggg]
    f8 << params[:faces][:hhh]
    f9 << params[:faces][:iii]
    f10 << params[:faces][:jjj]
    f11 << params[:faces][:kkk]
    f12 << params[:faces][:lll]
    file1 = f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12
    @face=Face.audit_task(file1,fmonth,anual,reporttyp)
    if reporttyp=="Monthly"
    redirect_to "/files/#{fmonth}_#{anual}_audit_report.csv"
    else 
    redirect_to "/files/#{anual}_audit_report.csv"
    end
   end
  def duplication
    @dup=Face.new
  end
  def duplication_process
    file1=params[:face][:file_1]
    filename=params[:face][:file_1].original_filename
    if params[:face][:file_1].original_filename =~ /.\.csv$/i
    @dup=Face.dups(file1)
    redirect_to "/files/Repetitive_output.csv"
    else
    redirect_to faces_vert_help_path
    end

  end
  def vertical
   @face=Face.new
  end

  def vert_process
    file1=params[:face][:file_1]
    filename=params[:face][:file_1].original_filename
    if params[:face][:file_1].original_filename =~ /.\.csv$/i
    @face=Face.verticals(file1)
    redirect_to "/files/Vertical_Output.csv"
    else 
    redirect_to faces_vert_help_path
    end
  end
  def compare
      @face=Face.new
  end
  def save_file
   file1=params[:face][:file_1]
   file2=params[:face][:file_2]
   filename=params[:face][:file_1].original_filename
   filename=params[:face][:file_2].original_filename
    if params[:face][:file_1].original_filename =~ /.\.csv$/i and params[:face][:file_2].original_filename =~ /.\.csv$/i
      @face=Face.com_vertical(file1,file2)
      @face=Face.comparison
      redirect_to "/files/Output_comparison.csv"
    else
      redirect_to faces_vert_help_path
    end
  end

=begin  def spellcheck
    @face=Face.new
  end
 
 def spell_process
   if params[:face][:file_1].original_filename =~ /.\.csv$/i and params[:face][:file_2].original_filename =~ /.\.csv$/i
      file1=params[:face][:file_1]
      filename=params[:face][:file_1].original_filename
      @face=Face.spell_check(file1,)
      redirect_to :action=>"/process/Speller.rb"
   else
      redirect_to faces_vert_help_path
   end
  end
=end
  def uom
      @face=Face.new
  end

  def uom_method
    file1=params[:face][:file_1]
    file2=params[:face][:file_2]
    filename=params[:face][:file_1].original_filename
    filename=params[:face][:file_2].original_filename
    if params[:face][:file_1].original_filename =~ /.\.csv$/i and params[:face][:file_2].original_filename =~ /.\.csv$/i
       @face=Face.uoms(file1,file2)
       redirect_to "/files/UOM_file_Output.csv"
    else 
      redirect_to faces_vert_help_path
    end
  end

 def pilot
file1=params[:face][:file3]
      file2=params[:face][:file4]

      filename=params[:face][:file3].original_filename
      filename=params[:face][:file4].original_filename
     
      @face=Face.pil2(file1,file2)
    
      unless @face.blank?

      flash[:notice] = "Your file has been successfully imported."

      redirect_to "/files/output.csv"
   
      else

       flash[:notice] = "Invalid file headers or file format"
     
       redirect_to :action=> "welookup"
    
      end
end

def consicutive
  @face=Face.new
end

  def consicutive_process
 if params[:face][:file_1].original_filename =~ /.\.csv$/i 
      file1=params[:face][:file_1]
      filename=params[:face][:file_1].original_filename
      @face=Face.consecutive(file1,filename)
      redirect_to "/files/Output_#{filename}"
   else
      redirect_to faces_vert_help_path
   end
  end

  def vert_help
      @face=Face.all
  end

  def result
      @face=Face.new
  end

  def help_ver
      @face=Face.new
  end

  def help_uom
      @face=Face.new
  end

end

app/helpers/faces_helper.rb
module FacesHelper
end

app/views/faces/audit_report.html.erb
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

</head>
<body>

<div id='hm'><%= link_to image_tag("/assets/hicon.png",height: '55', width:'55'),faces_index_path%></div>

<h4 align="center"><i>Audit Report</i></h4>


 <center><table class="table">

  <tr>
   <%= form_for(:faces, :url=>{:controller=>"faces", :action=>"audit_process" ,:method=>"get"}) do |f|%>
   
    <tr><td> <%= f.select :month, options_for_select([["Select Month", ""], "January","February","March","April", "May","June", "July","August","September","October","November","December"]) %> </td><td> <%= f.text_field :year ,:placeholder=>"Enter the Year",:required=>true%> </td><td> <%= f.select :reporttype, options_for_select([["Select Report Type", ""], "Monthly","Yearly"])%></td></tr>

        
    <tr>
    <td> <%= f.file_field :aa,:accept => 'text/csv',class: 'form-control',:onchange=>"ValidateSingleInput(this);",:onclick=>"setVisibility('txt', 'inline');"%></td>
       
       
    <td> <%= f.text_field :a ,:id=>'txt',:placeholder=>"Enter the WUI"%></td><td> <%= f.text_field :aaa ,:placeholder=>"Enter the Project Name",:id=>'pn'%></td></tr>
         
    <tr> 
    <td> <%= f.file_field :bb,:accept => 'text/csv',class: 'form-control',:onchange=>"ValidateSingleInput(this);",:onclick=>"setVisibility('txt1', 'inline');"%></td>
    <td> <%= f.text_field :b,:placeholder=>"Enter the WUI",:id=>'txt1'%> </td><td> <%= f.text_field :bbb ,:placeholder=>"Enter the Project Name",:id=>'pn'%></td> </tr>
    <tr> 
    <td> <%= f.file_field :cc,:accept => 'text/csv',class: 'form-control',:onchange=>"ValidateSingleInput(this);",:onclick=>"setVisibility('txt2', 'inline');"%></td>
    <td> <%= f.text_field :c,:placeholder=>"Enter the WUI",:id=>'txt2'%> </td><td> <%= f.text_field :ccc ,:placeholder=>"Enter the Project Name",:id=>'pn'%></td></tr>

    <tr>
    <td> <%= f.file_field :dd,:accept => 'text/csv',class: 'form-control',:onchange=>"ValidateSingleInput(this);",:onclick=>"setVisibility('txt3', 'inline');"%></td>
    <td> <%= f.text_field :d,:placeholder=>"Enter the WUI",:id=>'txt3'%> </td><td> <%= f.text_field :ddd ,:placeholder=>"Enter the Project Name",:id=>'pn'%></td></tr>

    <tr> 
    <td> <%= f.file_field :ee,:accept => 'text/csv',class: 'form-control',:onchange=>"ValidateSingleInput(this);",:onclick=>"setVisibility('txt4', 'inline');"%></td>
    <td> <%= f.text_field :e,:placeholder=>"Enter the WUI",:id=>'txt4'%> </td><td> <%= f.text_field :eee ,:placeholder=>"Enter the Project Name",:id=>'pn'%></td></tr>

    <tr> 
    <td> <%= f.file_field :ff,:accept => 'text/csv',class: 'form-control',:onchange=>"ValidateSingleInput(this);",:onclick=>"setVisibility('txt5', 'inline');"%></td>
    <td> <%= f.text_field :f,:placeholder=>"Enter the WUI",:id=>'txt5'%> </td><td> <%= f.text_field :fff ,:placeholder=>"Enter the Project Name",:id=>'pn'%></td></tr>

    <tr>
    <td> <%= f.file_field :gg,:accept => 'text/csv',class: 'form-control',:onchange=>"ValidateSingleInput(this);",:onclick=>"setVisibility('txt6', 'inline');"%></td>
    <td> <%= f.text_field :g,:placeholder=>"Enter the WUI",:id=>'txt6'%> </td><td> <%= f.text_field :ggg ,:placeholder=>"Enter the Project Name",:id=>'pn'%></td></tr>

    <tr>
    <td> <%= f.file_field :hh,:accept => 'text/csv',class: 'form-control',:onchange=>"ValidateSingleInput(this);",:onclick=>"setVisibility('txt7', 'inline');"%></td>
    <td> <%= f.text_field :h,:placeholder=>"Enter the WUI",:id=>'txt7'%> </td><td> <%= f.text_field :hhh ,:placeholder=>"Enter the Project Name",:id=>'pn'%></td></tr>

    <tr>
    <td> <%= f.file_field :ii,:accept => 'text/csv',class: 'form-control',:onchange=>"ValidateSingleInput(this);",:onclick=>"setVisibility('txt8', 'inline');"%></td>
    <td> <%= f.text_field :i,:placeholder=>"Enter the WUI",:id=>'txt8'%> </td><td> <%= f.text_field :iii ,:placeholder=>"Enter the Project Name",:id=>'pn'%></td></tr>

    <tr>
    <td> <%= f.file_field :jj,:accept => 'text/csv',class: 'form-control',:onchange=>"ValidateSingleInput(this);",:onclick=>"setVisibility('txt9', 'inline');"%></td>
    <td> <%= f.text_field :j,:placeholder=>"Enter the WUI",:id=>'txt9'%> </td><td> <%= f.text_field :jjj ,:placeholder=>"Enter the Project Name",:id=>'pn'%></td></tr>
    
    <tr>
    <td> <%= f.file_field :kk,:accept => 'text/csv',class: 'form-control',:id=>"f11",:onchange=>"ValidateSingleInput(this);",:onclick=>"setVisibility('txt10', 'inline');"%></td>
    <td> <%= f.text_field :k,:placeholder=>"Enter the WUI",:id=>'txt10'%> </td><td> <%= f.text_field :kkk ,:placeholder=>"Enter the Project Name",:id=>'pn'%></td></tr>

    <tr>
    <td> <%= f.file_field :ll,:accept => 'text/csv',class: 'form-control',:onchange=>"ValidateSingleInput(this);",:onclick=>"setVisibility('txt11', 'inline');"%></td>
    <td> <%= f.text_field :l,:placeholder=>"Enter the WUI",:id=>'txt11'%> </td><td> <%= f.text_field :lll ,:placeholder=>"Enter the Project Name",:id=>'pn'%></td></tr>
    

  <tr>
   <td> <%= f.submit "Submit",:class => "btn btn-info",:onclick=>"Validate()"%></td>
   
   <td><a href="http://192.168.1.52:3000/faces/help_ver"  target="popup"
  onclick="window.open('http://192.168.1.52:3000/faces/help_ver','popup','width=700,height=400'); return false;"> Help</a></td>
  </tr>

 <% end %>
</table></center>
<center><b>Note:Upload (.csv) Files only.</b></center>

</body>

</div>

</html>
<script language="JavaScript">
function setVisibility(id, visibility) {
document.getElementById(id).style.display = visibility;
}
</script>

app/views/faces/col_comp.html.erb
<h1>Faces#col_comp</h1>
<p>Find me in app/views/faces/col_comp.html.erb</p>

app/views/faces/compare.html.erb
<body>

<div id='hm'><%= link_to image_tag("/assets/hicon.png",height: '55', width:'55'),faces_index_path%></div>

<div id="shadow">

<div id='index'></div>

<div id='header'>

<div id="h1"><i>Audit & Shipment File Comparison</i></div></div>

<div id='content'>

<div class="table stripped custab">
<table class="table">

 <tr>
  <%= form_for([@face], :url=>{:controller=>"faces", :action=>"save_file"}) do |f|%>
  <td><%= f.label :file_1,"Audit_File" %></td>
  <td> <%= f.file_field :file_1,:accept => 'text/csv',:onchange=>"ValidateSingleInput(this);", class: 'form-control', :required => true%></td>
 </tr>

 <tr>
  <td><%= f.label :file_2,"Shipment_File" %></td>
  <td> <%= f.file_field :file_2,:accept => 'text/csv', class: 'form-control',:onchange=>"ValidateSingleInput(this);", :required => true%></td>
 </tr>



<tr>
  <td> <%= f.submit "Upload",:class => "btn btn-info"%></td>
  <td><a href="#"  target="popup"
  onclick="window.open('http://192.168.1.52:3000/faces/result','popup','width=700,height=400'); return false;"> Help</a></td>
 </tr>

 <% end %>

</table>
</div>

<center><b>Note:Upload (.csv) Files only.</b></center>

</div>

</div>

</body>

app/views/faces/help_uom.html.erb
<div id='uom_h'></div>
<!--div id='hb'><!-%= link_to image_tag("/assets/back4.jpeg",height: '45', width:'45'),faces_uom_path%></div>

app/views/faces/help_ver.html.erb
<div id="ver_h"></div>

<!--div id='hb'><!-%= link_to image_tag("/assets/back4.jpeg",height: '45', width:'45'),faces_vertical_path%--><!--/div-->

app/views/faces/index.html.erb
<div class="container">
<div id="shadow">

<div id="index"></div>

<div id="header">

<div id="h1"><i>User Interface</i></div>

</div>

<div id="content">
<table class="table stripped custab">
<ul>

<tr><td><li style="list-style-type:none"><%= link_to "Vertical Conversion",faces_vertical_path%></li></tr></td>

<tr><td><li style="list-style-type:none"><%= link_to "Audit & Shipment File Comparison",faces_compare_path%></li></tr></td>

<tr><td><li style="list-style-type:none"><%= link_to "UOM File Comparison",faces_uom_path%></li></tr></td>

<tr><td><li style="list-style-type:none"><%= link_to "Finding Consecutive Words",faces_consicutive_path%></li></tr></td>

<tr><td><li style="list-style-type:none"><%= link_to "Finding Repetitive entry in a cell",faces_duplication_path%></tr></td>

<tr><td><li style="list-style-type:none"><%= link_to "Audit Report",faces_audit_report_path%></li></tr></td>

<tr><td><li style="list-style-type:none"><%= link_to "We Lookup",faces_welookup_path%></li></tr></td>

</ul>

</div>
</table>
</div>

</div>
</div>

app/views/faces/result.html.erb
<div id='com_h'></div>
<!--div id='hb'><!-%= link_to image_tag("/assets/back4.jpeg",height: '45', width:'45'),faces_compare_path%></div>